### ISSUE TITLE
Work CheckList - KR

### ISSUE THREAD

**Issue by mmol93** [mmol93/PairAlarm#4]
## UI에 대한 작업 내용
- [ ] Splash 화면 만들기
- [ ] 로그인 화면 만들기
- [ ] MainColor 정하기
- [ ] 기본 틀 잡기 - viewPager2와 fragments 이용
- [ ] 알람 기능 넣기
기본적인 Layout은 MaidAlarm을 참조

## 알람에 대한 작업 내용
* 알람 추가는 Floating 버튼을 사용하기
  * Floating 버튼 역시 MaidAlarm에서 사용한 것 사용하기
* 알람 추가 후 데이터는 Room DB를 사용하여 저장
- [ ] 알람 기능이 제대로 작동하는지 확인하기
간단하게 알람 울리면 Activity 뜨게 하기
- [ ] 휴대폰을 껏다 켰을 때도 알람이 제대로 울리는지 확인하기
- [ ] 알람 수정기능 넣기
- [ ] 알람 삭제기능 넣기
